# Vagrantfile
Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "3072"
  end

  # Define the VM
  config.vm.define "superset-vm" do |vm|
    vm.vm.box = "ubuntu/bionic64"
    vm.vm.network "forwarded_port", guest: 80, host: 8080
    vm.vm.network "forwarded_port", guest: 8088, host: 8088
  end
end

